var hierarchy =
[
    [ "Backdrop", "class_backdrop.html", null ],
    [ "Block", "class_block.html", [
      [ "CastleBlock", "class_castle_block.html", null ],
      [ "MountainBlock", "class_mountain_block.html", null ]
    ] ],
    [ "Cannon", "class_cannon.html", null ],
    [ "Cannonball", "class_cannonball.html", null ],
    [ "Castle", "class_castle.html", null ],
    [ "CastleblockOLD", "class_castleblock_o_l_d.html", null ],
    [ "Circle", "class_circle.html", null ],
    [ "Game", "class_game.html", null ],
    [ "Graphic", "class_graphic.html", null ],
    [ "Input", "class_input.html", null ],
    [ "King", "class_king.html", null ],
    [ "Map", "class_map.html", null ],
    [ "Mix_Chunk", "struct_mix___chunk.html", null ],
    [ "Mountain", "class_mountain.html", null ],
    [ "Rectangle", "class_rectangle.html", null ],
    [ "SDL_ActiveEvent", "struct_s_d_l___active_event.html", null ],
    [ "SDL_AudioCVT", "struct_s_d_l___audio_c_v_t.html", null ],
    [ "SDL_AudioSpec", "struct_s_d_l___audio_spec.html", null ],
    [ "SDL_CD", "struct_s_d_l___c_d.html", null ],
    [ "SDL_CDtrack", "struct_s_d_l___c_dtrack.html", null ],
    [ "SDL_Color", "struct_s_d_l___color.html", null ],
    [ "SDL_Cursor", "struct_s_d_l___cursor.html", null ],
    [ "SDL_Event", "union_s_d_l___event.html", null ],
    [ "SDL_ExposeEvent", "struct_s_d_l___expose_event.html", null ],
    [ "SDL_JoyAxisEvent", "struct_s_d_l___joy_axis_event.html", null ],
    [ "SDL_JoyBallEvent", "struct_s_d_l___joy_ball_event.html", null ],
    [ "SDL_JoyButtonEvent", "struct_s_d_l___joy_button_event.html", null ],
    [ "SDL_JoyHatEvent", "struct_s_d_l___joy_hat_event.html", null ],
    [ "SDL_KeyboardEvent", "struct_s_d_l___keyboard_event.html", null ],
    [ "SDL_keysym", "struct_s_d_l__keysym.html", null ],
    [ "SDL_MouseButtonEvent", "struct_s_d_l___mouse_button_event.html", null ],
    [ "SDL_MouseMotionEvent", "struct_s_d_l___mouse_motion_event.html", null ],
    [ "SDL_Overlay", "struct_s_d_l___overlay.html", null ],
    [ "SDL_Palette", "struct_s_d_l___palette.html", null ],
    [ "SDL_PixelFormat", "struct_s_d_l___pixel_format.html", null ],
    [ "SDL_QuitEvent", "struct_s_d_l___quit_event.html", null ],
    [ "SDL_Rect", "struct_s_d_l___rect.html", null ],
    [ "SDL_ResizeEvent", "struct_s_d_l___resize_event.html", null ],
    [ "SDL_RWops", "struct_s_d_l___r_wops.html", null ],
    [ "SDL_Surface", "struct_s_d_l___surface.html", null ],
    [ "SDL_SysWMEvent", "struct_s_d_l___sys_w_m_event.html", null ],
    [ "SDL_SysWMinfo", "struct_s_d_l___sys_w_minfo.html", null ],
    [ "SDL_SysWMmsg", "struct_s_d_l___sys_w_mmsg.html", null ],
    [ "SDL_UserEvent", "struct_s_d_l___user_event.html", null ],
    [ "SDL_version", "struct_s_d_l__version.html", null ],
    [ "SDL_VideoInfo", "struct_s_d_l___video_info.html", null ],
    [ "Sound", "class_sound.html", null ],
    [ "Sprite", "class_sprite.html", [
      [ "AnimatedSprite", "class_animated_sprite.html", null ]
    ] ],
    [ "Tracer", "class_tracer.html", null ],
    [ "Uint64", "struct_uint64.html", null ]
];